Repository ProFile-org/ProFile-FE, pull requests merged in 2023-06, with the labels that each got.

#22 Khanh/refactor
  src/components/Card/InfoCard.component.tsx
  src/components/Skeleton/SkeletonCard.component.tsx
  src/components/Skeleton/index.ts
  src/components/Status/Status.component.tsx
  src/components/Table/Table.component.tsx
  src/constants/config.ts
  src/constants/routes.ts
  src/constants/status.ts
  src/containers/ImportDocumentContainer/ImportDocumentContainer.tsx
  src/containers/SignInFormContainer/SignInFormContainer.tsx
  src/hooks/useNavigateSelect.tsx
  src/hooks/usePagination.tsx
  src/index.css
  src/pages/DashboardPage/DashboardPage.tsx
  src/pages/emp/EmpDashboardPage/EmpDashboardPage.tsx
  src/pages/emp/EmpDocumentDetailPage/EmpDocumentDetailPage.tsx
  src/pages/emp/EmpDocumentPage/EmpDocumentPage.tsx
  src/pages/emp/EmpRequestDetailPage/EmpRequestDetailPage.tsx
  src/pages/emp/EmpRequestPage/EmpRequestPage.tsx
  src/pages/staff/StaffDashboardPage/StaffDashboardPage.tsx
  src/pages/staff/StaffDocumentDetailPage/StaffDocumentDetailPage.tsx
  src/pages/staff/StaffDocumentPage/StaffDocumentPage.tsx
  src/pages/staff/StaffFolderDetailPage/StaffFolderDetailPage.tsx
  src/pages/staff/StaffFolderPage/StaffFolderPage.tsx
  src/pages/staff/StaffLockerDetailPage/StaffLockerDetailPage.tsx
  src/pages/staff/StaffLockerPage/StaffLockerPage.tsx
  src/pages/staff/StaffRequestDetailPage/StaffRequestDetailPage.tsx
  src/pages/staff/StaffRequestPage/StaffRequestPage.tsx
  src/types/item.ts
  src/types/response.ts
  src/utils/formatter.ts
  src/utils/services/getUser.ts
Labels: enhancement

#45 chore: remove console.log
  Dockerfile
  src/pages/emp/EmpDashboardPage/EmpDashboardPage.tsx
Labels: refactor

#48 Khanh/staff crud
  src/components/ErrorTemplate/ErrorTemplate.component.tsx
  src/components/InputWithLabel/InputNumberWithLabel.component.tsx
  src/components/InputWithLabel/InputWithLabel.module.scss
  src/components/Navbar/Navbar.component.tsx
  src/containers/ImportDocumentContainer/ImportDocumentContainer.tsx
  src/index.css
  src/pages/Guards/RoleMapper.tsx
  src/pages/emp/EmpRequestCreatePage/EmpRequestCreatePage.tsx
  src/pages/staff/StaffDocumentDetailPage/StaffDocumentDetailPage.tsx
  src/pages/staff/StaffFolderDetailPage/StaffFolderDetailPage.tsx
  src/pages/staff/StaffLockerDetailPage/StaffLockerDetailPage.tsx
  src/pages/staff/StaffRequestDetailPage/StaffRequestDetailPage.tsx
  src/pages/staff/StaffRequestPage/StaffRequestPage.tsx
Labels: enhancement, refactor

#49 refactor(Dockerfile): dynamicly set api url when build
  Dockerfile
Labels: refactor
